#!/bin/sh

# Pre-Commit Workflow
#
# References:
#
# - https://github.com/okonet/lint-staged#command-line-flags

yarn build
cross-env LINT_STAGED=1 lint-staged --config=.lintstagedrc.json --relative --verbose
